[package]
name = "untex"
version = "0.2.0-alpha"
authors = ["Jérome Eertmans <jeertmans@icloud.com>"]
edition = "2021"
description = "Understand and manipulate TeX files with ease."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jeertmans/untex"
keywords = ["LaTeX", "TeX", "lexer", "detex", "opendetex"]

[lib]
name = "untex"
path = "src/lib/lib.rs"

[[bin]]
name = "untex"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
regex = "1"
clap = { version = "3.1.8", features = ["derive"] }
lazy_static = "1.4.0"
ptree = "0.4.0"
itertools = "0.10.3"
