[package]
name = "untex"
version = "0.3.0"
authors = ["Jérome Eertmans <jeertmans@icloud.com>"]
edition = "2021"
description = "Understand and manipulate TeX files with ease."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jeertmans/untex"
keywords = ["LaTeX", "TeX", "lexer", "detex", "opendetex"]

[lib]
name = "untex"
path = "src/lib/lib.rs"

[[bin]]
name = "untex"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
itertools = "0.10.5"
logos = "0.12.1"
thiserror = "1.0.38"
