on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: MSRV check

jobs:
  msrv_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Download cargo-msrv
        run: cargo install cargo-msrv

      - name: Check MSRV
        run: cargo msrv verify -- cargo check --all-features
